Joni/feature/96-add-cms-for-members-page
Alt-Org/Altzone-WebPages pull request #101
Opened 2024-09-25 12:22 UTC by Jonroi

Add starapi calls and implement attributes to sectionMembers component
Add nude CSS for later designing

2024-09-28 20:58 UTC, Jonroi reviewed
Strapi handling #2 ready for review

2024-10-03 13:30 UTC, leolabdev requested changes

2024-10-03 13:30 UTC, leolabdev commented on frontend-next-migration/src/widgets/SectionMembers/ui/MemberItem.tsx
### Suggestion:

The current implementation uses `onClick` for each link icon, but it would be more efficient and semantically correct to use the `Link` component (for example, from `next/link`). This would improve routing behavior and make the code cleaner by handling navigation with links directly.

Additionally, we can eliminate the repetitive `if` statements by introducing an `iconsMap` object, which will dynamically render the icons and links for each platform.

**What should be changed:**

1. Replace `onClick` handlers with `Link` to manage navigation more effectively.
2. Use an `iconsMap` to dynamically handle the rendering of icons and links, removing the need for multiple conditional statements.

Example of the improved code:

```tsx
import Link from 'next/link';
import { faGlobe, faGithub, faLinkedin, faFacebook, faInstagram, faEnvelope } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

const linksMap = {
  website: faGlobe,
  github: faGithub,
  linkedin: faLinkedin,
  facebook: faFacebook,
  instagram: faInstagram,
  email: faEnvelope
};

const MemberItem: FC<{ member: Member }> = ({ member }) => {
  return (
    <li key={member.id} className={cls.workmanComponent}>
      <div className={cls.memberRow}>
        <div className={cls.centerContainer}>
          <span className={cls.memberName}>{member.name}</span>
          <span className={cls.taskText}>{member.task}</span>
          <div className={cls.iconContainer}>
            <div className={cls.memberLogo}>
              {member.logo ? (
                <Image
                  src={member.logo}
                  alt={member.name}
                  className={cls.Logo}
                  width={500}
                  height={500}
                />
              ) : (
                <div className={cls.placeholderLogo} />
              )}
            </div>
            {Object.entries(linksMap).map(([key, icon]) => {
              const link = member[key as keyof Member];
              if (link) {
                const href = key === 'email' ? `mailto:${link}` : link;
                const target = key === 'email' ? '_self' : '_blank';
                return (
                  <Link key={key} href={href} passHref className={cls.clickableLogo} target={target} rel="noopener noreferrer>
                      <FontAwesomeIcon icon={icon} />
                  </Link>
                );
              }
              return null;
            })}
          </div>
        </div>
      </div>
    </li>
  );
};

export default MemberItem;

2024-10-03 13:30 UTC, leolabdev commented on frontend-next-migration/src/widgets/SectionMembers/model/mappers.ts
> +          ? `${process.env.NEXT_PUBLIC_STRAPI_HOST}${member.attributes.Logo.data.attributes.url}`
use envHelper

2024-10-03 13:30 UTC, leolabdev commented on frontend-next-migration/src/widgets/SectionMembers/model/membersApi.ts
We use an rtk request, it would be nice if this logic could also be used through it.

2024-10-03 13:30 UTC, leolabdev commented on frontend-next-migration/next.config.js
> +      { hostname: new URL(process.env.NEXT_PUBLIC_STRAPI_HOST).hostname },
use envHelper

2024-10-03 13:30 UTC, leolabdev commented on frontend-next-migration/src/widgets/SectionMembers/model/mappers.ts
> +          ? `${process.env.NEXT_PUBLIC_STRAPI_HOST}${member.attributes.Logo.data.attributes.url}`
And all the member (model) logic should be done in `entities/member`

2024-10-03 13:30 UTC, leolabdev commented on frontend-next-migration/src/preparedPages/MembersPage/ui/MembersPage.tsx
> + * @returns The `MembersPage` component is being returned. It is a functional component that renders a
the comment contains unnecessary information

2024-10-04 10:13 UTC, leolabdev requested changes

2024-10-04 10:13 UTC, leolabdev commented on frontend-next-migration/src/entities/Member/api/membersApi.ts
Please make in rtk style and dont forget to connect it to `app/_providers/StoreProvider` , you can see examples in other enties.

Here's how it might look:
```Typescript

import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import { envHelper } from '@/shared/const/envHelper';
import { Team } from '../model/types';
import { mapMembers, mapDepartments } from './mappers';

export const membersApi = createApi({
  reducerPath: 'membersApi',
  baseQuery: fetchBaseQuery({ baseUrl: envHelper.strapiApiUrl }),
  endpoints: (builder) => ({
    getTeams: builder.query<Team[], string>({
      // Since this is a GET request, we only need to define the query URL
      query: (locale = 'en') => {
        // Define the Strapi locale based on the input locale
        const strapiLocale = locale === 'fi' ? 'fi-FI' : 'en';
        // Build the API request URL for a GET request
        return `/teams?locale=${strapiLocale}&populate=departments.localizations,members.Logo,departments.members.Logo`;
      },
      transformResponse: (response: any, meta, locale: string) => {
        // Map the response data to the appropriate types
        const teams: Team[] = response.data.map((item: any) => {
          // Map team-level members (members who are not part of a specific department)
          let members = mapMembers(item.attributes.members?.data || []);
          
          // Map departments associated with the team
          const departments = mapDepartments(
            item.attributes.departments?.data || [],
            locale === 'fi' ? 'fi-FI' : 'en'
          );

          // Collect all member IDs that are assigned to departments
          const departmentMemberIds = departments.flatMap((dept) =>
            dept.members.map((member) => member.id)
          );

          // Filter out members that are already in a department from team-level members
          members = members.filter(
            (member) => !departmentMemberIds.includes(member.id)
          );

          // Return the mapped team with its members and departments
          return {
            id: item.id,
            name: item.attributes.name,
            members,
            departments,
          };
        });

        // Define the sort order for teams based on the locale
        const orderEn = [
          'Game Design',
          'Mentoring',
          'Administration',
          'Development',
          'Marketing',
        ];

        const orderFi = [
          'Pelit Suunnittelu',
          'Mentorointi',
          'Hallinto',
          'Kehitys',
          'Markkinointi',
        ];

        const order = locale === 'fi' ? orderFi : orderEn;

        // Sort teams based on the predefined order
        return teams.sort(
          (a: Team, b: Team) => order.indexOf(a.name) - order.indexOf(b.name)
        );
      },
    }),
  }),
});

export const { useGetTeamsQuery } = membersApi;

```

Dont forget to export this hook via public api (see https://github.com/Alt-Org/Altzone-WebPages/wiki/Project-Structure#between-modules-absolute-imports-via-indexts)

2024-10-04 10:14 UTC, leolabdev commented on frontend-next-migration/next.config.js
> +      { hostname: new URL(process.env.NEXT_PUBLIC_STRAPI_HOST).hostname },
is here some problem to with using the envHelper?

2024-10-04 10:17 UTC, leolabdev commented on frontend-next-migration/next.config.js
> +      { hostname: new URL(process.env.NEXT_PUBLIC_STRAPI_HOST).hostname },
in envHelper you have added : "strapiHost" , which is the "process.env.NEXT_PUBLIC_STRAPI_HOST", so just use envHelper.strapiHost instead ?

2024-10-04 17:07 UTC, leolabdev commented
pay attention also on 
![image](https://github.com/user-attachments/assets/cb1427da-78b7-49ba-ab02-c840cfaaccd5)

2024-10-05 10:42 UTC, leolabdev commented on frontend-next-migration/src/entities/Member/api/membersApi.ts
So I think you just need to do this mapping inside "transformResponse" and pass it out through a hook that generates rtk query like "useGetTeamsQuery"

2024-10-07 11:14 UTC, leolabdev approved these changes

2024-10-07 11:15 UTC, merged