fix: resolve 1px table border rendering issue on mobile by adjusting …
Alt-Org/Altzone-WebPages pull request #238
Opened 2024-10-28 09:47 UTC by juhaj77

## 📄 **Pull Request Overview**
This pull request addresses a table rendering issue in the Responsively App where inconsistent table borders are observed. The 1px border width does not render correctly across all device pixel ratios (DPR), leading to visual discrepancies along the table edges.

**Issue Number**: #152

## 🔧 **Changes Made**

- Adjusted table border thickness from `1px` to `0.25vh` to improve consistency across devices with different display pixel ratios (DPR).

---

## ✅ **Checklist Before Submission**

- **Functionality**: I have tested my code, and it works as expected.

---

## 📝 **Additional Information**

Provide any additional context or information that reviewers may need to know:

![Screenshot from 2024-10-28 11-43-53](https://github.com/user-attachments/assets/cc854c50-7b21-4ef9-abef-167a8d22fe97)

2024-10-29 11:43 UTC, leolabdev commented
@Skoivumaki , what do you think

2024-10-30 09:37 UTC, Skoivumaki requested changes
![image](https://github.com/user-attachments/assets/8ef372ec-fba5-47df-b3de-4be20afc8da7)
On 4K devices the border starts to look way too big. Its about 6px at this `vh`.
Use clamp to limit the max px size on large devices.
https://developer.mozilla.org/en-US/docs/Web/CSS/clamp
Something like this might work: `border-bottom: clamp(1px, 0.25vh, 3px);`

Using Responsively is good, but for some reason it doesnt have 4K option already built in so you need to add a custom res.

2024-10-30 16:06 UTC, Skoivumaki approved these changes

2024-10-31 13:22 UTC, leolabdev approved these changes

2024-10-31 13:23 UTC, merged