fixed issue with "Close" red button misalaigned.
Alt-Org/Altzone-WebPages pull request #242
Opened 2024-10-29 14:00 UTC by sappho911

## 📄 **Pull Request Overview**
Fix issues with red "Close" button being misaligned in Clan Overview on mobile.
Browser engines suffering from this issue: Chromium

**Issue Number**: [#187](https://github.com/Alt-Org/Altzone-WebPages/issues/187)

## 🔧 **Changes Made**

The button positioning in chromium browsers has been adjusted.

---

## ✅ **Checklist Before Submission**

- **Functionality**: I have tested my code, and it works as expected.

---

## 📝 **Additional Information**

![image](https://github.com/user-attachments/assets/0c2cd7eb-ca0d-4fce-8422-3c47da691216)

2024-10-29 17:06 UTC, Skoivumaki requested changes
Works as expected. Just remove testContainer and this is good for approval.

2024-10-29 17:06 UTC, Skoivumaki commented on frontend-next-migration/src/preparedPages/ClanPages/ui/_components/clanoverview/clanViewAndSearch/ClanSearchAndView.module.scss
> +.testContainer {
Remove unused code. This was left out when clan overview was being developed.

2024-10-30 16:12 UTC, Skoivumaki approved these changes

2024-10-31 13:22 UTC, leolabdev approved these changes
@Skoivumaki Trust you

2024-10-31 13:22 UTC, merged