Added AttributesPricing component, test, and stories files
Alt-Org/Altzone-WebPages pull request #288
Opened 2024-11-19 11:51 UTC by juhaj77

## 📄 **Pull Request Overview**
This pull request introduces the `AttributesPricing` component, which calculates the cost of upgrading levels. The maximum level is determined from statsPricingData, which is based on the currently available data.
### Key Features  
- **Level Range**:  
  The "From Level" and "To Level" range is dynamically set between the current value and the maximum value.  
- **Flexible Data Integration**:  
  The `statsPricingData` file supports rendering the cost table for the Hero Development Page.  
- **Rarity Class**:  
  The rarity class is required and can be one of the following numeric values: 1, 3, 5-8, 10. 
**Issue Number**: #267 

## 🔧 **Changes Made**

1. [Briefly describe changes you made]

2. [Any refactoring or clean-up tasks]

---

## ✅ **Checklist Before Submission**

- **Functionality**: I have tested my code, and it works as expected.
- **JSDoc**: I have added or updated JSDoc comments for all relevant code.
- **Debugging**: No `console.log()` or other debugging statements are left.
- **Clean Code**: Removed commented-out or unnecessary code.
- **Tests**: Added new tests or updated existing ones for the changes made.
- **Documentation**: Documentation has been updated (if applicable).

---

## 📝 **Additional Information**
![AttributesPricing](https://github.com/user-attachments/assets/0286df4b-095b-4b2d-b3a6-b605a5a7ecfa)

Provide any additional context or information that reviewers may need to know:

- **Screenshots**: [Include any screenshots or videos if the changes affect the UI]
- **Dependencies**: [Mention any new dependencies or breaking changes]
- **Known Issues**: [List any known issues or limitations]

2024-11-19 18:58 UTC, leolabdev requested changes
Hi, I would like your object to be able to process some class, for example HeroStatsPriceManager, since React should be free from such logic. I slightly transferred your solution so that there was no useEffect, and instead of useState I would use useReducer in this case.

Also in your solution there is a problem that when you change the characteristic, the initial minimum levels are somehow strangely bound, for example for speed the minimum level is 5 instead of 1, for impact force 4, for size 3... etc

![image](https://github.com/user-attachments/assets/a4fb4611-3b03-4981-b815-8d4f9eeb0d57)

2024-11-19 19:10 UTC, leolabdev commented
And @Jonroi and I would like to commend you, you came up with a very clever solution with the price calculation.

2024-11-21 13:15 UTC, juhaj77 commented
> Also in your solution there is a problem that when you change the characteristic, the initial minimum levels are somehow strangely bound, for example for speed the minimum level is 5 instead of 1, for impact force 4, for size 3... etc

This is about the default level. For example, if speed is already at level 5, the level range starts from there, so it doesn't need to be selected separately. It varies based on the character data.

2024-12-02 09:21 UTC, leolabdev requested changes

2024-12-02 09:21 UTC, leolabdev commented on frontend-next-migration/src/entities/Hero/model/stats/AttributesPricingHelper.tsx
> +import { Stat } from '../../ui/AttributesPricing3/AttributesPricingV3';
move this one to types folder

2024-12-02 09:46 UTC, leolabdev approved these changes

2024-12-02 09:46 UTC, merged