added HeroDevelopmentPage and HeroMenuAsDropdown
Alt-Org/Altzone-WebPages pull request #308
Opened 2024-12-09 14:48 UTC by juhaj77

## 📄 **Pull Request Overview**
Added HeroDevelopmentPage and its associated HeroMenuAsDropdown, which differs from the HeroNavMenuAsDropdown component, where the routing logic has been replaced with a callback function. The hero selected from the dropdown is set as the state of HeroDevelopmentPage. The component also has states adjusted by the AttributesPricing component. These states control the content displayed within HeroDevelopmentPage.

closes #280
## 🔧 **Changes Made**

1. [Briefly describe changes you made]
Added initializeHeroGroups hero-specific stat data.
2. [Any refactoring or clean-up tasks]

---

## ✅ **Checklist Before Submission**

- **Functionality**: I have tested my code, and it works as expected.
- **JSDoc**: I have added or updated JSDoc comments for all relevant code.
- **Debugging**: No `console.log()` or other debugging statements are left.
- **Clean Code**: Removed commented-out or unnecessary code.
- **Tests**: Added new tests or updated existing ones for the changes made.
Removed AttributesPricing.test.tsx. The AttributesPricing component has been modified to adjust external states, making it no longer testable as an isolated unit.
- **Documentation**: Documentation has been updated (if applicable).

---

## 📝 **Additional Information**

Provide any additional context or information that reviewers may need to know:

- **Screenshots**: [Include any screenshots or videos if the changes affect the UI]
- **Dependencies**: [Mention any new dependencies or breaking changes]
- **Known Issues**: [List any known issues or limitations]
Warning: Cannot update a component (`HeroDevelopmentPage`) while rendering a different component (`AttributesPricing3`)

![heeroKehitys](https://github.com/user-attachments/assets/5280fa25-c106-4497-91a4-544e0abecae2)

2024-12-09 19:11 UTC, leolabdev requested changes

2024-12-09 19:11 UTC, leolabdev commented on frontend-next-migration/src/entities/Hero/model/initializeHeroGroups.ts
> +import { statData } from '@/entities/Hero/model/stats/statsDataV2';
should be "@/entities/Hero" according to https://feature-sliced.design/

2024-12-09 19:11 UTC, leolabdev commented on frontend-next-migration/src/entities/Hero/ui/AttributesPricing3/AttributesPricingV3.tsx
> +import { statValue } from '@/entities/Hero/model/stats/statsDataV2';
should be "@/entities/Hero" according to https://feature-sliced.design/

2024-12-09 19:11 UTC, leolabdev commented on frontend-next-migration/src/features/NavigateHeroes/ui/HeroMenuAsDropdown.test.tsx
> +import HeroMenuAsDropdown from '@/features/NavigateHeroes/ui/HeroMenuAsDropdown';
instead "import HeroMenuAsDropdown from '@/features/NavigateHeroes/ui/HeroMenuAsDropdown';"  should be "./HeroMenuAsDropdown"

2024-12-09 19:11 UTC, leolabdev commented on frontend-next-migration/src/preparedPages/HeroDevelopmentPage/ui/HeroDevelopmentPage.tsx
> +import { BarChart } from '@/entities/Hero/ui/BarChart/BarChart';
should be "@/entities/Hero" according to https://feature-sliced.design/

2024-12-09 19:11 UTC, leolabdev commented on frontend-next-migration/src/preparedPages/HeroDevelopmentPage/ui/HeroDevelopmentPage.tsx
> +import { HeroWithGroup, HeroSlug, Stat } from '@/entities/Hero/types/hero';
should be "@/entities/Hero" according to https://feature-sliced.design/

2024-12-09 19:11 UTC, leolabdev commented on frontend-next-migration/src/preparedPages/HeroDevelopmentPage/ui/HeroDevelopmentPage.tsx
> +import { color, rarityClassNames } from '@/entities/Hero/model/stats/statsDataV2';
should be "@/entities/Hero" according to https://feature-sliced.design/

2024-12-09 19:11 UTC, leolabdev commented on frontend-next-migration/src/preparedPages/HeroDevelopmentPage/ui/HeroDevelopmentPage.tsx
> +import { statsPricingData } from '@/entities/Hero/model/stats/statsPricingData';
should be "@/entities/Hero" according to https://feature-sliced.design/

2024-12-09 19:11 UTC, leolabdev commented on frontend-next-migration/src/preparedPages/HeroDevelopmentPage/ui/HeroDevelopmentPage.tsx
> +import { AttributesPricing3 } from '@/entities/Hero/ui/AttributesPricing3/AttributesPricingV3';
should be "@/entities/Hero" according to https://feature-sliced.design/

2024-12-09 19:11 UTC, leolabdev commented on frontend-next-migration/src/preparedPages/HeroDevelopmentPage/ui/HeroDevelopmentPage.tsx
> +import HeroMenuAsDropdown from '@/features/NavigateHeroes/ui/HeroMenuAsDropdown';
should be "@/features/NavigateHeroes" according to https://feature-sliced.design/

2024-12-12 20:06 UTC, juhaj77 commented
![Screenshot from 2024-12-12 21-56-00](https://github.com/user-attachments/assets/763e3e7b-6bcd-4c7c-a887-64c8dfaa76ad)
 Now it look like this and imports are fixed.

2024-12-17 10:01 UTC, merged