Custom select menu for LangSwitcher
Alt-Org/Altzone-WebPages pull request #309
Opened 2024-12-09 20:26 UTC by Chromoprotein

## 📄 **Pull Request Overview**

closes 211

## 🔧 **Changes Made**

1. Made a custom drop-down select menu for switching languages.

2. Added the requested style improvements: aligned the text to left, made the arrow smaller with more spacing, improved the border's style cohesion, and made the mobile version look cleaner.

---

## ✅ **Checklist Before Submission**

- **Functionality**: I have tested my code, and it works as expected.
- **JSDoc**: I have added or updated JSDoc comments for all relevant code.
- **Debugging**: No `console.log()` or other debugging statements are left.
- **Clean Code**: Removed commented-out or unnecessary code.
- **Tests**: Added new tests or updated existing ones for the changes made.
- **Documentation**: Documentation has been updated (if applicable).

---

## 📝 **Additional Information**

<img width="576" alt="custom-menu" src="https://github.com/user-attachments/assets/b7890925-1d58-4d3f-ace7-3850c21f112b">

2024-12-10 11:16 UTC, Skoivumaki commented
@Chromoprotein is this a new PR? Did you do requested changes from the last one?

2024-12-10 11:21 UTC, Chromoprotein commented
@Skoivumaki Yes, sorry I made a new branch and PR because I had some git problems. I made the requested changes except the animation. Is it ok if that's a separate issue?

2024-12-10 11:23 UTC, Skoivumaki commented
@Chromoprotein Did you figure out the ident issue? 
> Is it ok if that's a separate issue?

Maybe if needed

2024-12-10 11:32 UTC, Chromoprotein commented
@Skoivumaki I noticed the mobile version was making the logout button's text next to it look misaligned, so I fixed that, but I'm not sure that was the problem tbh.

2024-12-10 12:23 UTC, Skoivumaki commented
> @Skoivumaki I noticed the mobile version was making the logout button's text next to it look misaligned, so I fixed that, but I'm not sure that was the problem tbh.

![image](https://github.com/user-attachments/assets/e4829edd-3c9d-4bca-9b55-1ef4c38c4404)
Notice how the button used to look. Now that the border matches the size of "log out", the spacing seems too much imo. I think this is what was meant with ident. I would reduce spacing between text and svg to not make the button seem so wide. Only for desktop, mobile is fine as is.

2024-12-10 12:25 UTC, Skoivumaki commented
@leolabdev clarification about the ident thing?

2024-12-12 11:02 UTC, leolabdev commented
It looks better, but I don't understand why the margins look different on mobile and desktop sizes.

![image](https://github.com/user-attachments/assets/a3fcd55b-047e-490c-ae59-23c2104c0d14)
![image](https://github.com/user-attachments/assets/e9138dfe-335a-464c-89c8-e29f06f469aa)

## VS

![image](https://github.com/user-attachments/assets/a9a9b98a-178f-405b-b8e3-acd35a345ab3)
![image](https://github.com/user-attachments/assets/6f564293-6b40-44a3-960e-1b725116261e)


Also, on the browser solution, you can see that the option and label are on the same level and aligned to the left. I think we should also stick to this. Also, now when hovering over it, this is not shown to the user at all.

2024-12-12 11:03 UTC, leolabdev requested changes
see my comments above

2024-12-16 21:35 UTC, Chromoprotein commented
<img width="381" alt="langswitcher changes" src="https://github.com/user-attachments/assets/eae86b46-bc33-44a3-a4e6-3ed7bb0a2cc4" />

How does it look now? The margins are the same on mobile and desktop, the option and label are on the same level and aligned to the left, and hovering is indicated by the text color.

2025-01-16 09:38 UTC, Jonroi approved these changes
I think this implementation works well enough for now—it functions properly on both desktop and mobile. Let’s move forward with it as-is, since our next step will involve a complete navbar redesign.

### Screenshots:
#### Desktop View:
<img src="https://github.com/user-attachments/assets/9d60493e-0e64-4101-8413-2b32b4287479" alt="Desktop View" width="50%">

#### Mobile View:
<img src="https://github.com/user-attachments/assets/bef045ea-8902-4c03-9103-787a44e859ef" alt="Mobile View" width="50%">

2025-01-23 11:10 UTC, Skoivumaki approved these changes

2025-01-23 11:28 UTC, Chromoprotein commented
@leolabdev It looks like this can't be merged until you approve it, could you please review? 🙂

2025-01-26 07:32 UTC, merged