Jarno/feature/298-responsive-flexbox-layout-for-clans-main-page
Alt-Org/Altzone-WebPages pull request #311
Opened 2024-12-10 15:48 UTC by Rutjake

## 📄 **Pull Request Overview**

closes 298

## 🔧 **Changes Made**

Created flexboxes for the page layout ([lng](helper)\clans\layout.tsx) and adjusted responsiveness and alignment in the CSS file (new file, ClanPageLayout.scss).

---

## ✅ **Checklist Before Submission**

- **Functionality**: I have tested my code, and it works as expected.
- 
Responsiveness worked in the browser and the flexbox size was adjusted according to the page's main menu.
---

## 📝 **Additional Information**

Provide any additional context or information that reviewers may need to know:

- **Screenshots**: [Include any screenshots or videos if the changes affect the UI]

![Flexbox_Desktop_ScreenShot](https://github.com/user-attachments/assets/10df99bf-c932-46d2-996d-a9e467edc91c)

![Flexbox_Mobile_ScreenShot](https://github.com/user-attachments/assets/3b40d2d6-d009-439c-a7cb-42d126dbcc89)

2024-12-12 05:03 UTC, Skoivumaki requested changes
Build is failing because of a typo. `import './ClanPageLayout.scss';` when it should be `import './clanPageLayout.scss';` but change the file name to keep good practice: `ClanPageLayout.scss`
We dont store CSS inside [lng], code for layout should be stored inside pages layer and should only be imported in [lng]. (see Auth for example: [lng]\(helper)\auth\layout.tsx) We have a place to store layouts but since this layout is Clan specific I think this will do for now.
![image](https://github.com/user-attachments/assets/2de706af-2b92-4006-9487-a02103dd4128)

About FSD folder scheme: [https://feature-sliced.design](https://feature-sliced.design)

To summarize:

- [x] Rename `clanPageLayout.scss` to `ClanPageLayout.scss`
- [ ] Move code related to layout to proper location
- [ ] Dont override the old layout yet, since it may break some clan elements.
- [ ] Make sure build and tests pass

2024-12-12 09:57 UTC, leolabdev commented
@Skoivumaki @Rutjake hey guys we use css(scss) modules  not pure css

2024-12-17 14:06 UTC, Skoivumaki approved these changes
Looks good and works as expected. Only thing missing was the export in index.ts for the layout itself, but I added that myself.

2024-12-18 10:52 UTC, leolabdev requested changes
please use for breakpoints the following below scss function:

![image](https://github.com/user-attachments/assets/5b8c8218-db84-4752-a6d0-a728ec4ec35f)

2025-01-08 07:05 UTC, Jonroi approved these changes
I read the latest comments from the reviewers and noted that the breakpoints have been used correctly and the previous tasks have been completed, so good work

2025-01-17 11:44 UTC, Skoivumaki approved these changes
same as above

2025-01-17 11:54 UTC, merged