Add furnitures page
Alt-Org/Altzone-WebPages pull request #312
Opened 2024-12-11 12:38 UTC by juho236

## 📄 **Pull Request Overview**

closes [#269]

## 🔧 **Changes Made**

1. Added the furniture pages with all the requested features
Features include:
- Main page for all sets.
- A page for each set with more detail and every piece belonging to said set.
- Search function to search furniture pieces with a keyword.
- Category page to filter pieces by category.

Full translations for English and Finnish

---

## ✅ **Checklist Before Submission**

- **Functionality**: I have tested my code, and it works as expected.
- **JSDoc**: I have added or updated JSDoc comments for all relevant code.
- **Debugging**: No `console.log()` or other debugging statements are left.
- **Clean Code**: Removed commented-out or unnecessary code.
- **Tests**: Added new tests or updated existing ones for the changes made.

---

## 📝 **Additional Information**

Screenshots of different features:

Main page: 
![image](https://github.com/user-attachments/assets/e4bd4c00-2817-40fc-8b40-38f8fdb93989)

Single set page:
![image](https://github.com/user-attachments/assets/35810c88-aaaf-40fc-8610-5d57c1b21894)

Piece cards:
![image](https://github.com/user-attachments/assets/62425f01-e789-4345-ab2c-2758394025a9)

Piece info:
![image](https://github.com/user-attachments/assets/34eb83ee-dcc7-4425-ad7a-2271a36e6892)

Search by category:
![image](https://github.com/user-attachments/assets/b8392548-ccd4-4d2d-9de8-dc7c3fb93b14)

Search by keyword:
![image](https://github.com/user-attachments/assets/63d69c3f-b03f-4185-8dc5-afc238338889)

Right now covers and posters are static which makes adding more very annoying.

2024-12-12 05:47 UTC, Skoivumaki requested changes
Build fails to compile. Something about types? Fix it first and make sure both build and tests pass.

2024-12-12 09:51 UTC, leolabdev requested changes
Hi, everything looks stylish. I'm still in the process of reviewing everything, but for now, please fix the issue where other elements jump or increase in size on hover. Perhaps the furniture elements themselves could be slightly smaller. Also, in my opinion, their large size doesn’t look very good on mobile devices.

2024-12-12 09:54 UTC, leolabdev commented
![image](https://github.com/user-attachments/assets/03aca1df-185f-424b-a6a7-1dd55dd97562)

2024-12-13 18:21 UTC, leolabdev approved these changes

2024-12-13 18:22 UTC, merged