SProkopios/feature/293-add-feedback-card-component
Alt-Org/Altzone-WebPages pull request #313
Opened 2024-12-11 14:07 UTC by SProkopios

## 📄 **Pull Request Overview**

closes #293

## 🔧 **Changes Made**

1. Created feedback card component with test, story and multi-language support.

2. [Any refactoring or clean-up tasks]: Css-file looks bit messy with all the !important command. This is thanks to google fonts import, which messed the whole css-file for some reason.

---

## ✅ **Checklist Before Submission**

- **Functionality**: I have tested my code, and it works as expected. ✅ Tested in storybook, test itself and in pages.
- **JSDoc**: I have added or updated JSDoc comments for all relevant code. ✅
- **Debugging**: No `console.log()` or other debugging statements are left. ✅
- **Clean Code**: Removed commented-out or unnecessary code. ✅
- **Tests**: Added new tests or updated existing ones for the changes made. ✅
- **Documentation**: Documentation has been updated (if applicable). ✅

---

## 📝 **Additional Information**

Provide any additional context or information that reviewers may need to know:

- **Screenshots**: [Include any screenshots or videos if the changes affect the UI]: -
- **Dependencies**: [Mention any new dependencies or breaking changes]: -

- **Known Issues**: [List any known issues or limitations]: Css-file bit messy because of google font import.

2024-12-11 15:36 UTC, Jonroi approved these changes
Everything is as planned and tests passed. Nice job!

2024-12-12 09:20 UTC, leolabdev requested changes
change feature name from "FeedbackCard" to "feedback"

features/feedback/ui (The card name remains the same.): 

![image](https://github.com/user-attachments/assets/eef9184d-b84a-4973-a3ac-dddd74a899fc)

Also every module should have API (index.ts), so make it:
features/feedback/index.ts

inside index.ts make FeebackCard export: 

export {default as FeedbackCard } from "path/to/FeedbackCard"


read more here: https://github.com/Alt-Org/Altzone-WebPages/wiki/6.-Project-Structure

2024-12-12 09:21 UTC, leolabdev requested changes

2024-12-12 09:21 UTC, leolabdev commented on frontend-next-migration/src/features/FeedbackCard/ui/FeedbackCard.tsx
> +export function FeedbackCard() {
change to export default

2024-12-12 14:52 UTC, leolabdev requested changes
duplication ? 
![image](https://github.com/user-attachments/assets/d145bf26-5d18-41d7-aad1-e7e995373e8b)

2024-12-12 14:55 UTC, leolabdev requested changes

2024-12-12 14:55 UTC, leolabdev commented on frontend-next-migration/src/features/FeedbackCard/ui/FeedbackCard.stories.tsx
> +    title: 'features/FeedbackCard',
features/feedback/FeedbackCard

2024-12-12 16:15 UTC, leolabdev approved these changes

2024-12-12 16:16 UTC, merged