Kaisa/enhancement/278 update gallery to work with cms integration
Alt-Org/Altzone-WebPages pull request #314
Opened 2024-12-11 15:42 UTC by kaisahakola

## 📄 **Pull Request Overview**

closes #278 

## 🔧 **Changes Made**

1. Replaced gallery's old API logic with Directus.

2. Updated gallery components to work with new API.
These components include:
- ImageWall
- SectionGallery (version 2)
- PictureGalleryPage

---

## ✅ **Checklist Before Submission**

- **Functionality**: I have tested my code, and it works as expected.
- **JSDoc**: I have added or updated JSDoc comments for all relevant code.
- **Debugging**: No `console.log()` or other debugging statements are left.
- **Clean code**: Removed commented-out or unnecessary code.
- **Tests**: Added new tests or updated existing ones for the changes made. 
---

2024-12-12 06:04 UTC, Skoivumaki commented
Build fails to compile. Fix it first and make sure both build and tests pass.

2024-12-12 12:33 UTC, leolabdev requested changes

2024-12-12 12:33 UTC, leolabdev commented on frontend-next-migration/src/entities/Gallery/api/useGetDirectusGalleryImages.ts
> +    getCategoryTranslation,
please use relative paths when work inside the same module

2024-12-12 12:33 UTC, leolabdev commented on frontend-next-migration/src/entities/Gallery/api/useGetDirectusGalleryImages.test.ts
> +import {
please use relative paths when work inside the same module

2024-12-12 12:33 UTC, leolabdev commented on frontend-next-migration/src/entities/Gallery/api/translations.ts
> +import { PhotoVersionTranslations, CategoryTranslations } from '@/entities/Gallery';
please use relative paths when work inside the same module

2024-12-12 12:33 UTC, leolabdev commented on frontend-next-migration/src/entities/Gallery/api/filterAndTransformImages.ts
> +import { PhotoObject, PhotoVersion } from '@/entities/Gallery';
please use relative paths when work inside the same module

2024-12-12 12:33 UTC, leolabdev commented on frontend-next-migration/src/entities/Gallery/ui/ImageWall/ImageWall.stories.tsx
> +import { mockImagesFull, mockImagesPreview, ImageWall } from '@/entities/Gallery';
please use relative paths when work inside the same module

2024-12-12 12:33 UTC, leolabdev commented on frontend-next-migration/src/entities/Gallery/ui/ImageWall/ImageWall.tsx
> +import { PhotoObject, PhotoVersion, filterAndTransformImages } from '@/entities/Gallery';
please use relative paths when work inside the same module

2024-12-12 12:33 UTC, leolabdev commented on frontend-next-migration/src/features/NavigateGalleries/ui/GalleryNavMenuAsDropdown.tsx
> +const categoriesEn: string[] = ['All', 'Nature', 'City', 'People', 'Technology'];
use api values instead

2024-12-15 08:47 UTC, leolabdev approved these changes

2024-12-15 08:47 UTC, merged