Implement directus to feedbackCard
Alt-Org/Altzone-WebPages pull request #323
Opened 2024-12-16 14:14 UTC by SProkopios

## 📄 **Pull Request Overview**

closes #307

## 🔧 **Changes Made**

1. Briefly describe changes you made:  Created a Feedback collection with the following fields:
feedbackText: Text, required.
rating: Integer, optional.
timestamp: DateTime, auto-generated. Configured roles and permissions to secure feedback data access. Integrated Feedback to directus with SDK

---

## ✅ **Checklist Before Submission**

- **Functionality**: I have tested my code, and it works as expected. ✅ * test and the pictures attached
- **JSDoc**: I have added or updated JSDoc comments for all relevant code.
- **Debugging**: No `console.log()` or other debugging statements are left. ✅
- **Clean Code**: Removed commented-out or unnecessary code. ✅
- **Tests**: Added new tests or updated existing ones for the changes made. ✅
- **Documentation**: Documentation has been updated (if applicable).

---

## 📝 **Additional Information**

Provide any additional context or information that reviewers may need to know:

- **Screenshots**: [Include any screenshots or videos if the changes affect the UI]:
![image](https://github.com/user-attachments/assets/d8abd1bc-5fb5-45c8-908b-077627ae077c)
![image](https://github.com/user-attachments/assets/1605f2c3-c37a-45b2-9cff-15abafc4d52b)
- **Dependencies**: [Mention any new dependencies or breaking changes]
- **Known Issues**: [List any known issues or limitations]: Should still modify FeedbackCard to call Api!

2024-12-16 16:38 UTC, leolabdev requested changes

2024-12-16 16:38 UTC, leolabdev commented on frontend-next-migration/src/entities/Feedback/api/feedbackApi.ts
> +export const feedbackApi = async (data: Feedback): Promise<boolean> => {
use galleryApi as an example 

![image](https://github.com/user-attachments/assets/ae5de3b2-b6d4-497a-b4a4-36accc52fe4f)

2024-12-17 14:32 UTC, SProkopios commented
use galleryApi as an example ✅

2024-12-18 11:12 UTC, leolabdev approved these changes

2024-12-18 11:12 UTC, merged